# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'blogwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_blogwindow(object):
    def setupUi(self, blogwindow):
        blogwindow.setObjectName("blogwindow")
        blogwindow.resize(579, 415)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/image/insect_128px_1168368_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/image/image/insect_128px_1168368_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        blogwindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(blogwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.authorcheck = QtWidgets.QCheckBox(self.centralwidget)
        self.authorcheck.setObjectName("authorcheck")
        self.horizontalLayout.addWidget(self.authorcheck)
        self.authortext = QtWidgets.QLineEdit(self.centralwidget)
        self.authortext.setObjectName("authortext")
        self.horizontalLayout.addWidget(self.authortext)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.titlecheck = QtWidgets.QCheckBox(self.centralwidget)
        self.titlecheck.setObjectName("titlecheck")
        self.horizontalLayout_2.addWidget(self.titlecheck)
        self.titletext = QtWidgets.QLineEdit(self.centralwidget)
        self.titletext.setObjectName("titletext")
        self.horizontalLayout_2.addWidget(self.titletext)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tagcheck = QtWidgets.QCheckBox(self.centralwidget)
        self.tagcheck.setObjectName("tagcheck")
        self.horizontalLayout_3.addWidget(self.tagcheck)
        self.tagtext = QtWidgets.QLineEdit(self.centralwidget)
        self.tagtext.setObjectName("tagtext")
        self.horizontalLayout_3.addWidget(self.tagtext)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.classcheck = QtWidgets.QCheckBox(self.centralwidget)
        self.classcheck.setObjectName("classcheck")
        self.horizontalLayout_4.addWidget(self.classcheck)
        self.classtext = QtWidgets.QLineEdit(self.centralwidget)
        self.classtext.setObjectName("classtext")
        self.horizontalLayout_4.addWidget(self.classtext)
        self.gridLayout.addLayout(self.horizontalLayout_4, 1, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.contentcheck = QtWidgets.QCheckBox(self.centralwidget)
        self.contentcheck.setObjectName("contentcheck")
        self.horizontalLayout_5.addWidget(self.contentcheck)
        self.contenttext = QtWidgets.QLineEdit(self.centralwidget)
        self.contenttext.setObjectName("contenttext")
        self.horizontalLayout_5.addWidget(self.contenttext)
        self.gridLayout.addLayout(self.horizontalLayout_5, 2, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.timecheck = QtWidgets.QCheckBox(self.centralwidget)
        self.timecheck.setObjectName("timecheck")
        self.horizontalLayout_6.addWidget(self.timecheck)
        self.timebegin = QtWidgets.QLineEdit(self.centralwidget)
        self.timebegin.setObjectName("timebegin")
        self.horizontalLayout_6.addWidget(self.timebegin)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.timeend = QtWidgets.QLineEdit(self.centralwidget)
        self.timeend.setObjectName("timeend")
        self.horizontalLayout_6.addWidget(self.timeend)
        self.gridLayout.addLayout(self.horizontalLayout_6, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.selectblog = QtWidgets.QPushButton(self.centralwidget)
        self.selectblog.setObjectName("selectblog")
        self.horizontalLayout_7.addWidget(self.selectblog)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.blog = QtWidgets.QTableWidget(self.centralwidget)
        self.blog.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.blog.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.blog.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.blog.setGridStyle(QtCore.Qt.SolidLine)
        self.blog.setRowCount(0)
        self.blog.setObjectName("blog")
        self.blog.setColumnCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.blog.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.blog.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.blog.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.blog.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.blog.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.blog.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.blog.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.blog.setHorizontalHeaderItem(7, item)
        self.blog.horizontalHeader().setVisible(True)
        self.blog.horizontalHeader().setCascadingSectionResizes(True)
        self.blog.horizontalHeader().setDefaultSectionSize(100)
        self.blog.horizontalHeader().setHighlightSections(True)
        self.blog.verticalHeader().setCascadingSectionResizes(True)
        self.verticalLayout.addWidget(self.blog)
        blogwindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(blogwindow)
        self.selectblog.clicked.connect(blogwindow.selectblog_click)
        QtCore.QMetaObject.connectSlotsByName(blogwindow)

    def retranslateUi(self, blogwindow):
        _translate = QtCore.QCoreApplication.translate
        blogwindow.setWindowTitle(_translate("blogwindow", "博文_数据库"))
        self.authorcheck.setText(_translate("blogwindow", "作者    "))
        self.titlecheck.setText(_translate("blogwindow", "博文题目"))
        self.tagcheck.setText(_translate("blogwindow", "标签    "))
        self.classcheck.setText(_translate("blogwindow", "分类    "))
        self.contentcheck.setText(_translate("blogwindow", "博文内容"))
        self.timecheck.setText(_translate("blogwindow", "发布时间"))
        self.label.setText(_translate("blogwindow", "到"))
        self.selectblog.setText(_translate("blogwindow", "查询"))
        self.blog.setSortingEnabled(True)
        item = self.blog.horizontalHeaderItem(0)
        item.setText(_translate("blogwindow", "博客编号"))
        item = self.blog.horizontalHeaderItem(1)
        item.setText(_translate("blogwindow", "作者"))
        item = self.blog.horizontalHeaderItem(2)
        item.setText(_translate("blogwindow", "博文题目"))
        item = self.blog.horizontalHeaderItem(3)
        item.setText(_translate("blogwindow", "标签"))
        item = self.blog.horizontalHeaderItem(4)
        item.setText(_translate("blogwindow", "分类"))
        item = self.blog.horizontalHeaderItem(5)
        item.setText(_translate("blogwindow", "发布时间"))
        item = self.blog.horizontalHeaderItem(6)
        item.setText(_translate("blogwindow", "评论数量"))
        item = self.blog.horizontalHeaderItem(7)
        item.setText(_translate("blogwindow", "文本内容"))

import res_rc
