# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(529, 540)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/image/insect_128px_1168368_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/image/image/insect_128px_1168368_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 2, 1, 1)
        self.maxcount = QtWidgets.QLineEdit(self.centralWidget)
        self.maxcount.setObjectName("maxcount")
        self.gridLayout_3.addWidget(self.maxcount, 2, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 1, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 2, 4, 1, 1)
        self.blogmainurl = QtWidgets.QPlainTextEdit(self.centralWidget)
        self.blogmainurl.setObjectName("blogmainurl")
        self.gridLayout_3.addWidget(self.blogmainurl, 1, 0, 1, 5)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 4, 1, 1)
        self.blogspider = QtWidgets.QPushButton(self.centralWidget)
        self.blogspider.setObjectName("blogspider")
        self.gridLayout_3.addWidget(self.blogspider, 4, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 4, 3, 1, 1)
        self.img = QtWidgets.QCheckBox(self.centralWidget)
        self.img.setObjectName("img")
        self.gridLayout_3.addWidget(self.img, 4, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.blog = QtWidgets.QTableWidget(self.centralWidget)
        self.blog.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.blog.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.blog.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.blog.setGridStyle(QtCore.Qt.SolidLine)
        self.blog.setRowCount(0)
        self.blog.setObjectName("blog")
        self.blog.setColumnCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.blog.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.blog.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.blog.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.blog.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.blog.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.blog.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.blog.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.blog.setHorizontalHeaderItem(7, item)
        self.blog.horizontalHeader().setVisible(True)
        self.blog.horizontalHeader().setCascadingSectionResizes(True)
        self.blog.horizontalHeader().setDefaultSectionSize(100)
        self.blog.horizontalHeader().setHighlightSections(True)
        self.blog.verticalHeader().setCascadingSectionResizes(True)
        self.gridLayout.addWidget(self.blog, 6, 0, 1, 4)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 5, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem7, 5, 2, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 1, 1, 1)
        self.showblog = QtWidgets.QPushButton(self.centralWidget)
        self.showblog.setObjectName("showblog")
        self.gridLayout.addWidget(self.showblog, 2, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem8, 2, 3, 1, 1)
        self.showblogwindow = QtWidgets.QPushButton(self.centralWidget)
        self.showblogwindow.setObjectName("showblogwindow")
        self.gridLayout.addWidget(self.showblogwindow, 2, 2, 1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 1, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 0, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem11, 0, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 1, 1, 1)
        self.commentspider = QtWidgets.QPushButton(self.centralWidget)
        self.commentspider.setObjectName("commentspider")
        self.gridLayout_2.addWidget(self.commentspider, 0, 1, 1, 2)
        self.comment = QtWidgets.QTableWidget(self.centralWidget)
        self.comment.setObjectName("comment")
        self.comment.setColumnCount(5)
        self.comment.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.comment.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.comment.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.comment.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.comment.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.comment.setHorizontalHeaderItem(4, item)
        self.gridLayout_2.addWidget(self.comment, 2, 0, 1, 5)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem12, 1, 2, 1, 3)
        self.showcommentwindow = QtWidgets.QPushButton(self.centralWidget)
        self.showcommentwindow.setObjectName("showcommentwindow")
        self.gridLayout_2.addWidget(self.showcommentwindow, 0, 3, 1, 1)
        self.gridLayout_2.setRowStretch(0, 1)
        self.gridLayout_2.setRowStretch(1, 1)
        self.gridLayout_2.setRowStretch(2, 7)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 2)
        self.verticalLayout.setStretch(2, 2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        self.blogspider.clicked.connect(MainWindow.blogspider_click)
        self.commentspider.clicked.connect(MainWindow.commentspider_click)
        self.blogmainurl.textChanged.connect(MainWindow.mainurl_change)
        self.maxcount.textChanged['QString'].connect(MainWindow.count_change)
        self.showblog.clicked.connect(MainWindow.showblog_click)
        self.showblogwindow.clicked.connect(MainWindow.showblogwindow_click)
        self.showcommentwindow.clicked.connect(MainWindow.showcommentwindow_click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "新浪微博爬虫小程序"))
        self.label.setText(_translate("MainWindow", "输入要爬取的博客主页地址"))
        self.maxcount.setText(_translate("MainWindow", "50"))
        self.label_3.setText(_translate("MainWindow", "输入要爬取的博文篇数（默认每个博主只取前50篇）"))
        self.blogspider.setText(_translate("MainWindow", "爬取博客"))
        self.img.setText(_translate("MainWindow", "需要图片"))
        self.blog.setSortingEnabled(True)
        item = self.blog.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "博客编号"))
        item = self.blog.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "作者"))
        item = self.blog.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "博文题目"))
        item = self.blog.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "标签"))
        item = self.blog.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "分类"))
        item = self.blog.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "发布时间"))
        item = self.blog.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "评论数量"))
        item = self.blog.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "文本内容"))
        self.label_2.setText(_translate("MainWindow", "博文信息表"))
        self.showblog.setText(_translate("MainWindow", "查看博客"))
        self.showblogwindow.setText(_translate("MainWindow", "数据库操作"))
        self.label_4.setText(_translate("MainWindow", "评论信息表"))
        self.commentspider.setText(_translate("MainWindow", "查看评论"))
        item = self.comment.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "评论编号"))
        item = self.comment.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "博客编号"))
        item = self.comment.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "作者"))
        item = self.comment.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "评论时间"))
        item = self.comment.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "评论内容"))
        self.showcommentwindow.setText(_translate("MainWindow", "数据库操作"))

import res_rc
